### ISSUE TITLE
Run info stats command problems

### ISSUE THREAD

**Issue by melokki** [silkjs/tedis#27]
Hello
I am trying to run the `info stats` command using tedis, but I does not work how I was expecting

I am running it like this:

```
const data = await tedis.command("INFO", "STATS");
```

the result I get is this:

```
# Stats
```

Am I doing something wrong?

I tried to run the command like this
```
const data = await tedis.command("INFO STATS");
```

but I don't get any output this way

**Comment by dasoncheng** [comment]
@melokki Thanks for your feedback. After testing, the data returned by the info instruction of redis was not generated in strict accordance with the coding specification, so there were some problems during the analysis. Now it has been compatible and updated to v0.1.8 and can be used normally

```ts
```

**Comment by melokki** [comment]
thank you very much @dasoncheng for your reply and for the rapid fix.
