### ISSUE TITLE
Use Tedis with SSL

### ISSUE THREAD

**Issue by hoffe86** [silkjs/tedis#33]
Hey
I try to use Tedis to load data from a Azure Redis cache from my node application.
Seems there is a problem with my code, a bug or missing support for SSL encrypted connections, because when using SSL Port 6380 instead of Port 6379 (no ssl) I running into following error:

errno: 'ECONNRESET',  
code: 'ECONNRESET',   
syscall: 'read'

**Comment by abdelrahmannasr** [comment]
Hey,
Any update for this bug, please

**Comment by dasoncheng** [comment]
@abdelrahmannasr Thanks for supporting `tedis`, "TSL/SSL" support has been included in the development plan and is estimated to be available on 2020/1/5

**Comment by dasoncheng** [comment]
We released a new version of `tedis`[0.1.11-rc.1](https://www.npmjs.com/package/tedis/v/0.1.11-rc.1)

```ts
const tedis = new Tedis({
  port: 6379,
  host: "127.0.0.1",
  tls: {
    key: fs.readFileSync(__dirname + "/client_server/client_key.pem"),
    cert: fs.readFileSync(__dirname + "/client_server/client_cert.pem")
  }
});
```

**Comment by abdelrahmannasr** [comment]
@dasoncheng am trying to use tedis0.1.11-rc.1 for ssl connection but I can't found tls option in the new version package

**Comment by kemicofa** [comment]
This feature just happened to be released when we decided to deploy our project with AWS. 👍

**Comment by dasoncheng** [comment]
@abdelrahmannasr  the declaration file has been updated on [0.1.11-rc.2](https://www.npmjs.com/package/tedis/v/0.1.11-rc.2)
![image](https://user-images.githubusercontent.com/16243342/74023112-d34d2280-49d9-11ea-8e45-a3fe0889cce9.png)
